name = "k5m-fashion"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "k5m-fashion-votes"
database_id = "a61d4250-9551-467c-8c2d-0860092c68c9"
